wandb:
  name: "EfficientNetB3"
  project: "Portugese Meals Classification"

random_seed: 0
img_shape: [128, 128, 3]
class_count: 23
model_name: EfficientNetB3

baseline_path: ./model/EfficientNetB3_baseline.h5
saved_model_baseline_path: ./model/SMbaseline/
pruned_path: ./model/EfficientNetB3_pruned.h5
tflite_path: ./model/EfficientNetB3_quantized.tflite
tensorrt_path: ./model/tensorrt/

# dataset
dataset:
  name: initial_dataset
  data_dir: ./data/raw/
  augmented_dir: ./data/augmented_compressed/
  csv_dir: ./data/csv/
  validation_ratio: 0.10
  test_ratio: 0.20

# train
train:
  epochs: 60
  batch_size: 50
  lr: 0.005
  label_smoothing: 0.1
  metrics: [accuracy]

# optimize model
optimize:
  epochs: 5
  batch_size: 50
  lr: 0.0001
  label_smoothing: 0.1
  metrics: [accuracy]

callbacks:
  EarlyStopping:
    min_delta: 0
    patience: 10
    verbose: 1
    restore_best_weights: True

  ReduceLROnPlateau:
    monitor: val_loss
    factor: 0.2
    patience: 3
    verbose: 1
    min_delta: 0.0001

  WandbCallback:
    monitor: val_loss
    save_model: True
    log_weights: True
    save_graph: True
